apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: deployment.yaml
- path: service.yaml
replicas:
- name: vote
  count: 7
images:
- name: schoolofdevops/vote
  newTag: v4
namespace: instavote
commonLabels:
  project: instavote
  env: staging
configMapGenerator:
- name: vote-options
  env: options.env